name: Deploy to Hostinger

on:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Adjust to match your server's PHP version

      - name: Install Dependencies (Composer)
        run: composer update --optimize-autoloader --no-dev 


      - name: Install NPM Dependencies & Build
        run: |
          npm install
          npm run build

      - name: Sync files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          local_path: './*'
          remote_path: '/public_html/'
          sftp_only: true





